// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS-K9_NeoyPYeOj8YMBgTb5ZZwvkqboS4',
    appId: '1:101321404515:web:b946bede5cf9155c244856',
    messagingSenderId: '101321404515',
    projectId: 'zypher-top-up-668e1',
    authDomain: 'zypher-top-up-668e1.firebaseapp.com',
    storageBucket: 'zypher-top-up-668e1.firebasestorage.app',
    measurementId: 'G-VY68FLXWZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoVoBcEQAXeeipLav-63NprPX1s0aTipM',
    appId: '1:101321404515:android:6966e74e55bbe050244856',
    messagingSenderId: '101321404515',
    projectId: 'zypher-top-up-668e1',
    storageBucket: 'zypher-top-up-668e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHrtX2gfPmO9DX2Bn0IvaZCE7-Z0lGKLI',
    appId: '1:101321404515:ios:5149f2ecfeb78aab244856',
    messagingSenderId: '101321404515',
    projectId: 'zypher-top-up-668e1',
    storageBucket: 'zypher-top-up-668e1.firebasestorage.app',
    iosBundleId: 'com.example.zypherTopUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHrtX2gfPmO9DX2Bn0IvaZCE7-Z0lGKLI',
    appId: '1:101321404515:ios:5149f2ecfeb78aab244856',
    messagingSenderId: '101321404515',
    projectId: 'zypher-top-up-668e1',
    storageBucket: 'zypher-top-up-668e1.firebasestorage.app',
    iosBundleId: 'com.example.zypherTopUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS-K9_NeoyPYeOj8YMBgTb5ZZwvkqboS4',
    appId: '1:101321404515:web:d2549ec814c45197244856',
    messagingSenderId: '101321404515',
    projectId: 'zypher-top-up-668e1',
    authDomain: 'zypher-top-up-668e1.firebaseapp.com',
    storageBucket: 'zypher-top-up-668e1.firebasestorage.app',
    measurementId: 'G-SK9DPFDTPC',
  );
}
